// Builds bench/BENCHMARKS.md: every benchmark result in one file.
//   node bench/all.mjs
import fs from "node:fs";
import { execSync } from "node:child_process";

const run = (cmd) => execSync(cmd, { encoding: "utf8" }).trim();
const load = (f) => fs.readFileSync(f, "utf8").trim().split("\n").map((l) => JSON.parse(l));
const totals = run("node bench/totals.mjs");
const claudeCode = run("node bench/final.mjs");
const desktop = run("node bench/desktop/report.mjs")
  .split("\n").filter((l) => !/^# |^Headless Claude Code|^Runs: \d+/.test(l)).join("\n")
  .replace(/^## /gm, "### ").trim();

const longMd = run("node bench/long/report.mjs");
const effortMd = run("node bench/effort-report.mjs");
const effortRuns = load("bench/results/effort/runs.jsonl");
const longRuns = load("bench/long/results/runs.jsonl");
const rounds = ["round1", "round2", "round3", "round4"].map((r) => load(`bench/results/${r}/runs.jsonl`));
const deskRuns = load("bench/desktop/results/runs.jsonl");
const allRuns = rounds.flat().length + deskRuns.length + longRuns.length + effortRuns.length;
const spend = rounds.flat().reduce((s, r) => s + (r.cost_usd || 0), 0) + deskRuns.reduce((s, r) => s + (r.cost || 0), 0) + longRuns.reduce((s, r) => s + (r.cost || 0), 0) + effortRuns.reduce((s, r) => s + (r.cost_usd || 0), 0);
const roundCost = (i) => rounds[i].reduce((s, r) => s + (r.cost_usd || 0), 0).toFixed(2);

const md = `# token-saver benchmarks

All benchmark results for both plugins in one place. Generated by \`node bench/all.mjs\` from the raw run logs in \`bench/results/\` and \`bench/desktop/results/\`.

**Bottom line:** on **Opus**, the same work cost **about 13% less** with the plugins, consistently across short tasks, chat and long sessions. On **Sonnet** there's **no saving**: within noise on short tasks, and 12% *more* in long coding sessions. Overall, across everything measured: **about 6% less**.

**Effort is a bigger lever than the plugin.** Lowering Claude Code's effort from the default (\`medium\`) to \`low\` cut cost by **26% on Opus** and **12% on Sonnet**, with every quality check still passing but fewer tests written on big features. High effort cost 21–36% more. The installer now defaults to low effort, and \`/token-saver:deep\` runs a single request at high effort. Quality checks passed in almost every run with and without the plugins; see the caveats on tests and handoff notes below.

- Environment: Claude Code 2.1.294, headless (\`claude -p\`), models Sonnet 5.5 and Opus 5.5.
- Every run starts from a fresh copy of the material, and each setup (with and without the plugin) gets the same tasks, run 3 times.
- Quality is checked automatically (tests pass, required facts present), so a cheaper run that breaks things doesn't count as a win.
- ${allRuns} runs in total across all rounds, costing $${spend.toFixed(2)}.

## 1. Total cost comparison

Shipped configuration only: Claude Code plugin with the router off (the default), and the desktop plugin as released.

${totals}

With a $100 credit, mostly on Opus: the same work costs about $87, so the credit covers roughly 15% more work. Mostly on Sonnet: no saving; don't install it for cost reasons alone. The biggest lever remains model choice: the same coding work cost 2–3.4× more on Opus than on Sonnet.

## 2. Claude Code plugin (\`token-saver\`)

Coding work on a sample wallet/betting backend (plain Node, about 20 modules and 238 tests). It includes a ~190 KB legacy module, a 450 KB data file, a 1.3 MB log and verbose test output, so there's waste to avoid.

| Task | Prompt (short) | Quality check |
|---|---|---|
| Fix failing tests | Find and fix the bug causing 2 failing tests | All tests pass, tests not modified |
| Add refund feature | Refund a DEBIT by transaction id, once only, plus API route and tests | All tests pass, new tests added, refund in service and API |
| Large feature | Bonus/wagering module: grant, progress from bets, completion, expiry, forfeit, 3 API routes, tests | All tests pass, ≥8 new tests, \`src/bonus\`, API routes, bets integration |
| Explain | How is payout computed, which rounding mode, which function | Names the function and HALF_EVEN, no files changed |
| Rename | \`userId\` → \`accountId\` across src and tests | All tests pass, no \`userId\` left |

### Results (mean cost per task, 3 runs per cell)

${claudeCode}

Sonnet numbers are from round 1, Opus numbers from round 3. The large-feature "with plugin" column is from round 4, after the router was made opt-in.

### How the Claude Code plugin got here

| Round | Change | Spend | Finding |
|---|---|---|---|
| 1 | v1.3 on Sonnet + Opus | $${roundCost(0)} | The router never fired, because Opus writes code through the shell (\`python3 - <<EOF\`, \`sed -i\`), not Edit/Write. Opus was still ~10–20% cheaper from the session rules. Sonnet showed no change: this Claude Code version already reads files selectively and trims test output. |
| 2 | Router also catches shell-written code | $${roundCost(1)} | The router fired, and the feature task got **34% more expensive**. A blocked write has already been generated (and paid for) in Opus output, and then Sonnet writes it again. |
| 3 | Delegate large jobs upfront only; block only very large writes; added the large-feature task | $${roundCost(2)} | Small and medium tasks were 11–19% cheaper (the router didn't fire). The large feature was **31% more expensive**: Opus ignored the upfront rule and wrote the implementation itself, and only the test file got routed. |
| 4 | Router made opt-in (off by default) | $${roundCost(3)} | Large feature **14% cheaper** than without the plugin. |

**Router conclusion:** with current models, a hook can't move Opus's code-writing to Sonnet. Hooks only see a tool call after Opus has generated it, and instructions to delegate upfront weren't followed reliably. The router is kept as an opt-in experiment. For Opus planning with Sonnet coding, switch models yourself (\`/model opusplan\`, or plan on Opus and then \`/model sonnet\`).

## 3. Desktop plugin (\`token-saver-desktop\`)

Chat-style work, using headless Claude Code with the plugin loaded as a stand-in for the desktop app (same models and plugin mechanism, different system prompt). The material is a ~24k-token vendor contract with specific facts buried in boilerplate, plus an email draft.

| Scenario | Quality check |
|---|---|
| Question about the long contract (notice period, late-payment interest, liability cap) | All three facts correct |
| General question (optimistic vs pessimistic locking) | ≥4 of 6 key points |
| Revise one aggressive paragraph of an email | Facts kept (date, amount, deadline), tone softened |
| 9-message conversation about the contract, run three ways: without plugin, with plugin, and with plugin + \`/handoff\` after message 5 then \`/resume\` in a fresh chat | 6 fact checks across messages 2–9 |

${desktop}

- Answers were 30–50% shorter with the plugin, with every fact still present.
- **Handoff/resume didn't pay off in a 9-message chat.** Messages after the handoff cost about half as much, but writing the note (~$0.03) and rebuilding context in the new chat (Claude re-read the contract) cost more than that saved. Rough break-even is about 6–10 further messages.
- Note on costs: for resumed sessions, Claude Code reports cost as a running total for the session. The runner records per-message costs as differences between those totals.

## 4. Long sessions (Claude Code plugin)

A 19-request coding day on the sample project: overview, refund, summary endpoint, amount limits, daily deposit limit, a settlement question, cash-out, a refactor, a turnover report, pagination, account freezing, stake limit, idempotent credits, a router question, open-bets endpoint, README docs, fix failing tests, a concurrency question, and a changelog of everything changed. Each request continues the same session (\`--resume\`), like a real working day. Quality check: all tests pass, all 12 features present, and the final changelog lists at least 5 changes.

${longMd}

- **The context never got big.** Claude Code grew the context by only 2–4k tokens per request, peaking at 53–93k after 19 requests. The plugin's 80k handoff threshold was barely reached, and the guards fired 0–2 times per session, because Claude Code already reads selectively and trims output.
- **Sonnet: the plugin cost 12% more** in long sessions (+5% in the identical "handoff at 80k" arm, where no handoff happened either). With nothing to block, the extra rules are just overhead.
- **Opus: 11% cheaper**, the same pattern as short tasks, but with fewer new tests written (63 vs 77 on average).
- **Forcing a handoff at 50k** made Sonnet sessions 4% cheaper than without the plugin, but **the handoff lost history**: the final changelog listed only 5 changes instead of 13 (one run failed the check). The handoff note has since been changed to keep every change, one line each; that fix hasn't been re-benchmarked.

## 5. Effort levels

Claude Code's effort setting (\`--effort\`, \`/effort\`, \`effortLevel\`) controls how much the model reasons, how many tool calls it makes, and how thorough it is. The default on Sonnet 5.5 and Opus 5.5 is \`medium\`, and every other benchmark here ran at that default. This round runs the same 5 coding tasks with no plugin at low, medium and high effort.

${effortMd}

- **Low effort saves the most of anything measured:** 26% on Opus and 12% on Sonnet. It does this mainly by writing less: output tokens dropped 25–40%.
- **Quality held on the checks, but thoroughness dropped.** On the large feature, low effort wrote 13 new tests on Opus vs 31 at medium and 36 at high. If tests matter, use \`/token-saver:deep\` (high effort for one request) for big features.
- **High effort isn't free insurance:** 21–36% more, mostly from writing many more tests (Sonnet: 54 vs 21 on the large feature).
- The plugin and low effort weren't measured together. Both work mainly by shortening output, so their savings likely overlap rather than add up.

## 6. Caveats

- These are synthetic projects and documents, a single user, and 3 runs per cell. Differences of ±10% on tasks costing $0.03–0.10 are within run-to-run noise.
- The desktop plugin was measured in Claude Code, not in the desktop app itself.
- Long sessions were measured with 19 requests (Opus: 2 runs per setup). Even longer days, sessions spanning breaks (cache expiry), and auto-compaction weren't measured.
- The "be terse" rules may trim thoroughness on big jobs. On the large feature, Opus with the plugin wrote fewer new tests on average (28 vs 36), though all checks passed.

## 7. Reproduce

\`\`\`bash
node bench/run.mjs --models sonnet,opus --runs 3 --budget 15     # Claude Code plugin
node bench/desktop/run.mjs --models sonnet,opus --runs 3 --budget 15   # desktop plugin
node bench/long/run.mjs --models sonnet,opus --runs 3 --budget 20      # long sessions
node bench/run.mjs --configs effort-low,effort-medium,effort-high --out bench/results/effort --budget 15   # effort levels
node bench/all.mjs                                                 # rebuild this file
\`\`\`

Runs bill the account the \`claude\` CLI is signed into. \`--budget\` caps the total spend.
`;
fs.writeFileSync("bench/BENCHMARKS.md", md);
console.log(`Wrote bench/BENCHMARKS.md (${md.split("\n").length} lines)`);
